# -*- coding: utf-8 -*-
"""script_glossario_e_dicionario.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1_JhQwRC1eeZOcqXMY7DxLaxkZKmq1eoy
"""

# ============================================================
# GERA 04_glossario_e_dicionario.xlsx FORMATADO
# 4ª Etapa – Governança de Dados SwiftBank
# ============================================================

!pip install openpyxl --quiet

from openpyxl import Workbook
from openpyxl.styles import Font, PatternFill, Alignment, Border, Side
from openpyxl.utils import get_column_letter

# ============================================================
# DADOS
# ============================================================

# ---------- ABA 1: GLOSSARIO ----------
glossario = [
    ["nome", "definicao", "contexto_de_uso", "responsavel", "dominio", "termos_relacionados", "status"],
    ["Cliente Ativo", "Pessoa PF ou PJ com status_conta = Ativa e ao menos uma transação efetivada nos últimos 90 dias", "Marketing, Crédito, Financeiro", "Data Owner Crédito", "Crédito", "Cliente Inativo, Transação Efetivada", "Aprovado"],
    ["Cliente Inativo", "Cliente com conta Inativa ou sem movimentação há mais de 90 dias", "Marketing, Crédito", "Data Owner Crédito", "Crédito", "Cliente Ativo", "Aprovado"],
    ["Cliente PF", "Pessoa física titular de conta no SwiftBank", "Cadastro, Crédito", "Data Owner Cadastro", "Cadastro", "Cliente PJ, CPF", "Aprovado"],
    ["Cliente PJ", "Pessoa jurídica titular de conta no SwiftBank", "Cadastro, Crédito", "Data Owner Cadastro", "Cadastro", "Cliente PF, CNPJ", "Aprovado"],
    ["Conta Corrente", "Conta bancária de movimentação livre oferecida pelo SwiftBank", "Produtos, Operações", "Data Owner Produtos", "Produtos", "Conta Poupança, Transação", "Aprovado"],
    ["Empréstimo", "Operação de crédito com valor, prazo e juros definidos", "Crédito, Financeiro", "Data Owner Crédito", "Crédito", "Score de Crédito, Inadimplência", "Aprovado"],
    ["Score de Crédito", "Pontuação de 0 a 1000 que indica probabilidade de pagamento", "Crédito", "Data Owner Crédito", "Crédito", "Empréstimo, Inadimplência", "Aprovado"],
    ["Apólice", "Contrato de seguro vinculado a um cliente", "Produtos, Operações", "Data Owner Produtos", "Produtos", "Cliente PF, Cliente PJ", "Rascunho"],
    ["Transação Efetivada", "Operação financeira concluída com sucesso", "Financeiro, Crédito", "Data Owner Financeiro", "Financeiro", "Cliente Ativo, Conta Corrente", "Aprovado"],
    ["Receita", "Valor total recebido pelo SwiftBank em um período", "Financeiro", "Data Owner Financeiro", "Financeiro", "Transação Efetivada", "Aprovado"],
    ["Inadimplência", "Situação de cliente com pagamento em atraso além do prazo contratual", "Crédito, Financeiro", "Data Owner Crédito", "Crédito", "Empréstimo, Score de Crédito", "Aprovado"],
    ["Dado Pessoal Sensível", "Dado que revela origem racial, convicção religiosa, saúde, biometria, entre outros (LGPD art. 5º, II)", "Jurídico, Compliance", "DPO", "Jurídico", "Dado Pessoal, Consentimento", "Aprovado"],
    ["Consentimento de Marketing", "Autorização expressa do cliente para receber comunicações de marketing", "Marketing, Jurídico", "Data Owner Marketing", "Marketing", "Dado Pessoal, Finalidade", "Aprovado"],
]

# ---------- ABA 2: DICIONARIO_DADOS ----------
dicionario = [
    ["tabela", "camada", "coluna", "tipo", "descricao", "confidencialidade", "dado_pessoal", "responsavel"],
    # bz_clientes
    ["bz_clientes", "bronze", "id_cliente", "string", "Identificador único do cliente", "Interna", "Não", "Eng. Dados"],
    ["bz_clientes", "bronze", "nome_completo", "string", "Nome completo do cliente", "Restrita", "Sim", "Data Owner Cadastro"],
    ["bz_clientes", "bronze", "data_nascimento", "date", "Data de nascimento", "Restrita", "Sim", "Data Owner Cadastro"],
    ["bz_clientes", "bronze", "tipo_pessoa", "string", "PF ou PJ", "Interna", "Não", "Data Owner Cadastro"],
    ["bz_clientes", "bronze", "segmento", "string", "Varejo, Premium ou Empresarial", "Interna", "Não", "Data Owner Marketing"],
    ["bz_clientes", "bronze", "data_abertura_conta", "date", "Data de abertura da conta", "Interna", "Não", "Data Owner Operações"],
    ["bz_clientes", "bronze", "status_conta", "string", "Ativa, Inativa ou Encerrada", "Interna", "Não", "Data Owner Operações"],
    ["bz_clientes", "bronze", "produto_principal", "string", "Produto principal do cliente", "Interna", "Não", "Data Owner Produtos"],
    ["bz_clientes", "bronze", "cidade", "string", "Cidade do cliente", "Restrita", "Sim", "Data Owner Cadastro"],
    ["bz_clientes", "bronze", "consentimento_marketing", "string", "Sim ou Não", "Restrita", "Sim", "Data Owner Marketing"],
    # sl_clientes
    ["sl_clientes", "silver", "id_cliente", "string", "Identificador único do cliente", "Interna", "Não", "Eng. Dados"],
    ["sl_clientes", "silver", "nome_completo", "string", "Nome padronizado (title case)", "Restrita", "Sim", "Business Steward Cadastro"],
    ["sl_clientes", "silver", "data_nascimento", "date", "Data de nascimento (tipo date)", "Restrita", "Sim", "Business Steward Cadastro"],
    ["sl_clientes", "silver", "idade", "int", "Idade calculada a partir da data de nascimento", "Interna", "Não", "Business Steward Cadastro"],
    ["sl_clientes", "silver", "tipo_pessoa", "string", "PF ou PJ (validado)", "Interna", "Não", "Business Steward Cadastro"],
    ["sl_clientes", "silver", "segmento", "string", "Segmento padronizado", "Interna", "Não", "Business Steward Marketing"],
    ["sl_clientes", "silver", "status_conta", "string", "Status padronizado", "Interna", "Não", "Business Steward Operações"],
    ["sl_clientes", "silver", "consentimento_marketing", "boolean", "Consentimento convertido para booleano", "Restrita", "Sim", "Business Steward Marketing"],
    # gd_clientes_ativos
    ["gd_clientes_ativos", "gold", "id_cliente", "string", "Identificador único", "Interna", "Não", "Eng. Dados"],
    ["gd_clientes_ativos", "gold", "nome_completo", "string", "Nome do cliente ativo", "Restrita", "Sim", "Data Owner Crédito"],
    ["gd_clientes_ativos", "gold", "flag_ativo", "boolean", "True se cliente ativo (regra padronizada)", "Interna", "Não", "Data Owner Crédito"],
    ["gd_clientes_ativos", "gold", "data_ultima_transacao", "date", "Data da última transação efetivada", "Interna", "Não", "Data Owner Financeiro"],
    # bz_transacoes
    ["bz_transacoes", "bronze", "id_transacao", "string", "Identificador único da transação", "Interna", "Não", "Eng. Dados"],
    ["bz_transacoes", "bronze", "id_cliente", "string", "Identificador do cliente", "Interna", "Não", "Eng. Dados"],
    ["bz_transacoes", "bronze", "vlr_transacao", "float", "Valor da transação", "Restrita", "Não", "Data Owner Financeiro"],
    ["bz_transacoes", "bronze", "dt_transacao", "date", "Data da transação", "Interna", "Não", "Data Owner Financeiro"],
    ["bz_transacoes", "bronze", "moeda", "string", "Moeda da transação (BRL, USD)", "Interna", "Não", "Data Owner Financeiro"],
    # sl_transacoes
    ["sl_transacoes", "silver", "id_transacao", "string", "Identificador único", "Interna", "Não", "Eng. Dados"],
    ["sl_transacoes", "silver", "id_cliente", "string", "Identificador do cliente", "Interna", "Não", "Eng. Dados"],
    ["sl_transacoes", "silver", "vlr_transacao_brl", "float", "Valor convertido para BRL", "Restrita", "Não", "Business Steward Financeiro"],
    ["sl_transacoes", "silver", "dt_transacao", "date", "Data padronizada", "Interna", "Não", "Business Steward Financeiro"],
    # gd_metricas_credito
    ["gd_metricas_credito", "gold", "id_cliente", "string", "Identificador do cliente", "Interna", "Não", "Eng. Dados"],
    ["gd_metricas_credito", "gold", "vlr_total_transacionado", "float", "Soma das transações do cliente", "Restrita", "Não", "Data Owner Crédito"],
    ["gd_metricas_credito", "gold", "qtd_transacoes", "int", "Quantidade de transações", "Interna", "Não", "Data Owner Crédito"],
    ["gd_metricas_credito", "gold", "data_referencia", "date", "Data de referência do cálculo", "Interna", "Não", "Data Owner Crédito"],
]

# ---------- ABA 3: LINHAGEM ----------
linhagem = [
    ["origem", "destino", "transformacao_aplicada"],
    ["bz_clientes", "sl_clientes", "Limpeza de tipos (data_nascimento como date), padronização de nome (title case), cálculo de idade, conversão de consentimento para booleano, validação de tipo_pessoa e status_conta"],
    ["sl_clientes", "gd_clientes_ativos", "Aplicação da regra de Cliente Ativo: status_conta = Ativa E ao menos uma transação nos últimos 90 dias → criação da flag_ativo"],
    ["bz_transacoes", "sl_transacoes", "Harmonização de moeda (conversão para BRL), padronização de data, validação de valores"],
    ["sl_transacoes", "gd_metricas_credito", "Agregação por cliente: soma de vlr_transacao_brl, contagem de transações, definição de data_referencia"],
    ["gd_clientes_ativos", "gd_metricas_credito", "Cruzamento por id_cliente para enriquecer métricas de crédito com flag_ativo"],
]

# ---------- ABA 4: DIAGNOSTICO_METADADOS ----------
diagnostico = [
    ["indicador", "valor", "observacao"],
    ["Total de linhas no CSV", "(preencher após rodar script)", "metadados_tabelas_swiftbank.csv"],
    ["% completude - descricao", "(preencher)", "Campos vazios tratados como nulos"],
    ["% completude - confidencialidade", "(preencher)", "Campos vazios tratados como nulos"],
    ["% completude - dado_pessoal", "(preencher)", "Campos vazios tratados como nulos"],
    ["% completude - responsavel", "(preencher)", "Campos vazios tratados como nulos"],
    ["Linhas com camada inválida", "(preencher)", "Fora de bronze/silver/gold"],
    ["Descrições com ≤ 3 palavras", "(preencher)", "Indicador de baixa qualidade"],
    ["", "", ""],
    ["LEITURA DE NEGÓCIO", "", ""],
    ["", "O diagnóstico de qualidade de metadados identificou que as 3 tabelas com pior qualidade são [A], [B] e [C]. A tabela [A] apresenta o maior número de descrições curtas (≤ 3 palavras) e campos sem responsável definido, comprometendo rastreabilidade e accountability. A tabela [B] tem lacunas na coluna confidencialidade, essencial para classificação de dados pessoais e conformidade com a LGPD. A tabela [C] concentra campos sem dado_pessoal preenchido, dificultando a aplicação do princípio do acesso mínimo. Recomenda-se priorizar essas três tabelas para correção, mobilizando Data Owners e Stewards, com prazo de 30 dias e vinculação à diretriz D3 da Política de Acesso e Qualidade.", ""],
]

# ---------- ABA 5: PLANO_ACAO ----------
plano_acao = [
    ["problema", "tabela", "responsavel", "prazo", "diretriz_politica"],
    ["Descrições com ≤ 3 palavras", "[tabela A]", "Business Steward", "30 dias", "D3 – Regras de qualidade antes do go-live"],
    ["Campos sem responsável", "[tabela B]", "Data Owner", "30 dias", "D3 – Regras de qualidade antes do go-live"],
    ["Campos sem confidencialidade", "[tabela B]", "Data Owner + Segurança", "30 dias", "D2 – Criptografia"],
    ["Campos sem dado_pessoal", "[tabela C]", "DPO + Data Owner", "30 dias", "D1 – Aprovação de acesso"],
    ["Camada inválida", "[tabela X]", "Eng. Dados", "15 dias", "D3 – Regras de qualidade antes do go-live"],
    ["Divergência de definição (data_referencia)", "gd_clientes_ativos e gd_metricas_credito", "Business Steward", "45 dias", "D3 – Regras de qualidade antes do go-live"],
]

# ============================================================
# CRIAÇÃO DO ARQUIVO FORMATADO
# ============================================================

wb = Workbook()

# Estilos
header_font = Font(bold=True, color="FFFFFF", size=12)
header_fill = PatternFill("solid", fgColor="1F4E78")
sub_fill = PatternFill("solid", fgColor="D9E1F2")
destaque_fill = PatternFill("solid", fgColor="FFF2CC")
border = Border(
    left=Side(style="thin"), right=Side(style="thin"),
    top=Side(style="thin"), bottom=Side(style="thin")
)
wrap = Alignment(wrap_text=True, vertical="top")

def escreve_aba(ws, dados, titulo):
    ws.title = titulo
    for i, linha in enumerate(dados, start=1):
        for j, valor in enumerate(linha, start=1):
            cell = ws.cell(row=i, column=j, value=valor)
            cell.border = border
            cell.alignment = wrap
            if i == 1:
                cell.font = header_font
                cell.fill = header_fill
            elif j == 1:
                cell.font = Font(bold=True)
                cell.fill = sub_fill
    # Ajustar largura
    for col in ws.columns:
        max_len = max(len(str(c.value)) if c.value else 0 for c in col)
        ws.column_dimensions[get_column_letter(col[0].column)].width = min(max_len + 2, 55)

# Criar abas
escreve_aba(wb.active, glossario, "Glossario")
escreve_aba(wb.create_sheet(), dicionario, "Dicionario_Dados")
escreve_aba(wb.create_sheet(), linhagem, "Linhagem")
escreve_aba(wb.create_sheet(), diagnostico, "Diagnostico_Metadados")
escreve_aba(wb.create_sheet(), plano_acao, "Plano_Acao")

# Aba extra: Diagrama_Linhagem (vazia, para colar o PNG)
ws_diag = wb.create_sheet("Diagrama_Linhagem")
ws_diag["A1"] = "Cole aqui o PNG do diagrama de linhagem exportado do Draw.io"
ws_diag["A1"].font = Font(bold=True, italic=True)
ws_diag.column_dimensions["A"].width = 60

# Salvar
wb.save("04_glossario_e_dicionario.xlsx")
print("✅ Arquivo '04_glossario_e_dicionario.xlsx' gerado com sucesso!")
print("📋 Abas criadas: Glossario, Dicionario_Dados, Linhagem, Diagnostico_Metadados, Plano_Acao, Diagrama_Linhagem")

# Download no Colab
try:
    from google.colab import files
    files.download("04_glossario_e_dicionario.xlsx")
    print("📥 Download iniciado.")
except ImportError:
    print("📁 Arquivo salvo na pasta atual.")